### ISSUE TITLE
Do not work with singularity 3.0.3+ds on Debian/Testing

### ISSUE THREAD

**Issue by Trophime** [singularityhub/motd#2] opened 2019-05-21 15:37 UTC
Hi,
can you confirm that motd is not working with singularity 3.0.3?
I've tried basic greeting example.

Best
C

```
trophime@xxx:~/Downloads$ sudo singularity build greeting.sif greeting.def 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:9ff7e2e5f967fb9c4e8099e63508ab0dddebe3f820d08ca7fd568431b0d10c0e
 41.74 MiB / 41.74 MiB [====================================================] 0s
Copying blob sha256:59856638ac9f32d4caa0f5761b2597fe251642786fdfe1b917ddbb074b890c29
 848 B / 848 B [============================================================] 0s
Copying blob sha256:6f317d6d954b9a59c54b2cb09e1f30cd3e872796e431cd2ceac5ed570beb2939
 526 B / 526 B [============================================================] 0s
Copying blob sha256:a9dde5e2a643eca8fde0eed52f4aed31f3ecd9c1b2f24d5e3729cd8d2ae68177
 168 B / 168 B [============================================================] 0s
Copying config sha256:fc6c43cc1861761c74aff1dea266142a6a80ad491d673220fc70e7c7ffd80786
 2.42 KiB / 2.42 KiB [======================================================] 1s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ sed -i 2iecho Hello, ${USER}!; /.singularity.d/actions/shell
+ sed -i 3iecho; /.singularity.d/actions/shell
INFO:    Creating SIF file...
INFO:    Build complete: greeting.sif
trophime@xxx:~/Downloads$ singularity shell greeting.sif 
Singularity greeting.sif:~/Downloads> exit
trophime@xxx:~/Downloads$ singularity --version
singularity version 3.0.3+ds
```

**Comment by vsoch** [comment] 2019-05-21 15:41
Checking now! I just shelled into a 3.1 container to verify that `/.singularity.d/actions/shell` is there (it is) so I'll try to reproduce your error right now, give me a few minutes!

**Comment by vsoch** [comment] 2019-05-21 15:50
This looks like a bug - it's written when we build, and then it seems to be overwritten again. I'll open an issue and link here.

**Comment by vsoch** [comment] 2019-05-21 15:56
This is a bug with Singularity, I've opened an issue, and it's up to the maintainers to address, sorry for the crappy discovery! https://github.com/sylabs/singularity/issues/3590

**Comment by Trophime** [comment] 2019-05-21 16:21
No problem ;)

**Comment by Trophime** [comment] 2019-05-22 09:19
Hi,
this morning I've tried to create the singularity image with your docker image -namely, I use the 2.4 image -(BTW an example on how to create an image with the singularity docker will be great for dummy like me).

Running the image with singularity 3, no motd appears
But it works fine with singularity 2.4.2...

**Comment by vsoch** [comment] 2019-05-22 09:26
@Trophime if you look in the Sylabs thread, this is happening because at runtime, they are generating those files on the fly. It doesn't matter what is built there, whether it be with Singularity or Docker - it gets replaced by that. I'm fighting for this on the thread, and if you feel that it's important (I think it's important) you should pipe in there as well. If we don't argue our case, it won't be fixed.

**Closed as completed** 2019-05-22 21:20 UTC
